version: '3.8'

services:
  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      # - wordpress2
      # - wordpress3

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: senha_segura
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  # wordpress2:
  #   image: wordpress:5.4.2-php7.2-apache
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: wp
  #     WORDPRESS_DB_PASSWORD: senha_segura
  #     WORDPRESS_DB_NAME: wordpress
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   depends_on:
  #     - db

  # wordpress3:
  #   image: wordpress:5.4.2-php7.2-apache
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: wp
  #     WORDPRESS_DB_PASSWORD: senha_segura
  #     WORDPRESS_DB_NAME: wordpress
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   depends_on:
  #     - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: senha_segura
      MYSQL_ROOT_PASSWORD: senha_segura
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
